### ISSUE TITLE
Implement Default for everything

### ISSUE THREAD

**Issue by graydon** [stellar/rs-stellar-xdr#21]
Unfortunately derive(Default) only works on structs, but xdrpp produces a default constructor for tagged unions which default-constructs the discriminant (which I think 0-initializes the discriminant enum via scalar initialization in C++ which is maybe a touch risky except in practice we always define a 0-valued discriminant). In rust's case you'd have to pick one but picking the first enum case is probably harmless and it's frequently useful -- it's just "writing what the user would write in that case, transitively..."

**Comment by leighmcculloch** [comment]
I didn't include default in the derive lists of the structs or unions because I don't think we should shortcut defining defaults for applications that use the xdr. The lack of it doesn't stop applications from choosing a default if they need a default value. What will this break with the way stellar-core is written? Maybe this will force core to be safer?

**Comment by leighmcculloch** [comment]
We discussed offline. We'll reopen if we discover it is too inconvenient without it.
